name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '**'  # Triggers on pull requests to any branch
  push:
    branches:
      - main  # Triggers on pushes to the main branch

jobs:
  # Job for Code Reviews (Pull Requests)
  code_review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test (Up to 'test' phase)
        run: mvn clean test

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-review-artifacts
          path: |
            target/surefire-reports/
            target/checkstyle-result.xml
            target/rewrite/reports/
            target/site/jacoco/

  # Job for Pushes to Main (Production Readiness)
  build_and_release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build, Test, and Package (Up to 'package' phase)
        run: mvn clean package

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: production-artifacts
          path: |
            target/*.jar
            target/site/apidocs/
            target/surefire-reports/
            target/checkstyle-result.xml
            target/rewrite/reports/
            target/site/jacoco/